title: "Мой Простой Магазин"
description: "Тестовый магазин на Jekyll и CSV"
url: "https://serhii50.github.io"
baseurl: "/simple-shop"
theme: simple-shop-theme-mini
# theme: simple-shop-theme-tailwind
plugins:
  - jekyll-seo-tag

# Настройки магазина
whatsapp_phone: "380501234567"
telegram_user: "Serhii_K"
currency: "грн."

permalink: pretty

page_gen:
  - data: 'products'
    template: 'product'
    name: 'slug'
    dir: 'product'
    extension: 'html'
